---
- name: Check for a2ensite util
  shell: "command -v a2ensite >/dev/null 2>&1"
  changed_when: False

- name: Create vhost folders
  file:
    path: "{{ vhost_base_path }}/{{ item['host'] }}"
    state: directory
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites

- name: Copy deploy key
  copy:
    src="{{ item['gitkey'] }}"
    dest="/tmp/{{ item['host'] }}_rsa"
    follow=yes
    owner="{{ item['user'] }}"
    group="{{ item['group'] }}"
    mode=600
  with_items: vhost_sites
  when: "item['gitkey']|default('') != ''"

- name: Clone data folder
  git: repo="{{ item['git'] }}"
       dest="{{ vhost_base_path }}/{{ item['host'] }}/public_html"
       version=master
       accept_hostkey=yes
       depth=5
       force=yes
       key_file=/tmp/{{ item['host'] }}_rsa
  with_items: vhost_sites
  when: "item['git']|default('') != ''"

- name: Create data folder
  file:
    path: "{{ vhost_base_path }}/{{ item['host'] }}/public_html"
    state: directory
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites
  when: "item['git']|default('') == ''"

- name: Create log folder
  file:
    path: "{{ vhost_base_path }}/{{ item['host'] }}/logs"
    state: directory
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites

- name: Create apache2 vhosts
  template:
    src: apache2/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ item['host'] }}.conf
  with_items: vhost_sites

- name: Create default index.html
  template:
    src: apache2/index.html.j2
    dest: "{{ vhost_base_path }}/{{ item['host'] }}/public_html/index.html"
    owner: "{{ item['user'] }}"
    group: "{{ item['group'] }}"
  with_items: vhost_sites
  when: "item['git']|default('') == ''"

- name: Enable apache2 vhosts
  shell: "a2ensite {{ item['host'] }}.conf"
  notify: Apache reload
  with_items: vhost_sites
  when: "item['disabled']|default(false) != True"
